; Per-title overclock profiles in this folder (one .ini file per game).
; <TID>.ini

; Example:
; BOTW: DRAM OC in handheld for free performance

; The Legend of Zelda Breath of the Wild (01007EF00011E000)
; File: 01007EF00011E000.ini
; [values]
; handheld_mem=1996

